language: php

php:
- 7.1

services:
- mysql

before_script:
- cp .env.travis .env
- mysql -e 'create database testing_db;'
- composer self-update
- composer install --no-interaction
- pear install pear/PHP_CodeSniffer
- git clone https://github.com/klaussilveira/phpcs-psr /usr/share/php/PHP/CodeSniffer/Standards/PSR
- phpcs --config-set default_standard PSR
- phpenv rehash
- nvm install 7.7.1
- npm install npm@latest -g
- npm install -g jshint
- npm install
- phpcs -w --config-set severity 3
- php artisan key:generate
- php artisan migrate --seed

script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/assets/js/modules/*

notifications:
email:
    recipients:
        - marcel@prox-web.nl
    on_success: always
    on_failure: always
